In [28]:
import pandas as pd
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from feature_engine.outliers import Winsorizer
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_squared_error

import joblib
import warnings
warnings.filterwarnings("ignore")

In [29]:
dataset = pd.read_csv("clv_dataset.csv")
dataset.head()

,customer_id,age,gender,city,region,tenure_months,recency_days,frequency_orders,total_spent,avg_order_value,...,email_click_rate,loyalty_points,customer_segment,complaints,satisfaction_score,churn_risk,referral_count,avg_session_time,last_login_days,future_clv
0,1,45,Male,Bangalore,North,34,130,11,22049.35,1939.69,...,0.177,1077,Budget,0,4.7,0.126,1,16.91,116,48482.24
1,2,55,Female,Hyderabad,East,29,115,12,9864.60,930.01,...,0.081,694,Budget,0,3.1,0.178,4,11.15,57,36361.03
2,3,61,Male,Pune,South,11,195,15,27296.93,1546.24,...,0.184,999,Regular,0,3.6,0.231,1,25.61,116,46998.61
3,4,43,Female,Mumbai,Central,32,40,11,14348.10,1493.76,...,0.340,254,Budget,0,1.6,0.156,2,17.64,77,44372.90
4,5,60,Male,Mumbai,West,14,17,13,14451.23,1246.99,...,0.555,332,Budget,0,3.5,0.000,0,14.54,14,48491.85

In [30]:
x = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

In [31]:
numeric_feature = x.select_dtypes(exclude=["object"]).columns
catag_feature = x.select_dtypes(include=["object"]).columns

In [32]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("winsorizer", Winsorizer(capping_method="iqr", tail="both", fold=1.5)),
    ("scaler", MinMaxScaler())
])

In [33]:
catag_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(drop="first", handle_unknown="ignore", sparse_output=False))
])

In [34]:
preprocess_pipeline = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_feature),
    ("catag", catag_pipeline, catag_feature)
])

In [35]:
clean = preprocess_pipeline.fit(x)

In [36]:
Clean_data = pd.DataFrame(clean.transform(x))

In [37]:
Clean_data.head()

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
0,0.00000,0.529412,0.471429,0.354396,0.166667,0.278862,0.518775,0.305566,0.326697,0.515300,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.00001,0.725490,0.400000,0.313187,0.208333,0.112663,0.217689,0.201680,0.094926,0.147064,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.00002,0.843137,0.142857,0.532967,0.333333,0.350439,0.401448,0.330903,0.323162,0.417540,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.00003,0.490196,0.442857,0.107143,0.166667,0.173818,0.385799,0.526506,0.456262,0.429295,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.00004,0.823529,0.185714,0.043956,0.250000,0.175225,0.312212,0.427357,0.227452,0.221358,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [38]:
joblib.dump(clean, "knn_preprocess_pipeline.pkl")

['knn_preprocess_pipeline.pkl']

In [39]:
joblib.load("knn_preprocess_pipeline.pkl")

ColumnTransformer(transformers=[('numeric',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('winsorizer',
                                                  Winsorizer(capping_method='iqr',
                                                             fold=1.5,
                                                             tail='both')),
                                                 ('scaler', MinMaxScaler())]),
                                 Index(['customer_id', 'age', 'tenure_months', 'recency_days',
       'frequency_orders', 'total_spent', 'avg_order_value', 'max_order_value',
       'min_order_value', 'las...
       'loyalty_points', 'complaints', 'satisfaction_score', 'churn_risk',
       'referral_count', 'avg_session_time', 'last_login_days'],
      dtype='object')),
                                ('catag',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 Index(['gender', 'city', 'region', 'product_category', 'payment_method',
       'customer_segment'],
      dtype='object'))])

In [40]:
x_train, x_test, y_train, y_test = train_test_split(
    Clean_data, y, test_size=0.2, random_state=42
)

In [41]:
# model = KNeighborsRegressor(
#     n_neighbors=5,
#     weights="distance",
#     metric="minkowski"
# )

knn = KNeighborsRegressor()

In [42]:
param_grid = {
    "n_neighbors": [3, 5, 7, 9, 11, 15],
    "weights": ["uniform", "distance"],
    "metric": ["euclidean", "manhattan"]
}

In [43]:
random_search = RandomizedSearchCV(
    estimator=knn,
    param_distributions=param_grid,
    n_iter=10,
    scoring="r2",
    cv=3,
    random_state=42,
    n_jobs=-1
)

In [44]:
random_search.fit(x_train, y_train)

RandomizedSearchCV(cv=3, estimator=KNeighborsRegressor(), n_jobs=-1,
                   param_distributions={'metric': ['euclidean', 'manhattan'],
                                        'n_neighbors': [3, 5, 7, 9, 11, 15],
                                        'weights': ['uniform', 'distance']},
                   random_state=42, scoring='r2')

In [45]:
best_knn = random_search.best_estimator_
print("Best Parameters:", random_search.best_params_)

Best Parameters: {'weights': 'distance', 'n_neighbors': 11, 'metric': 'manhattan'}

In [46]:
# model.fit(x_train, y_train)

In [47]:
y_train_pred = best_knn.predict(x_train)
y_test_pred = best_knn.predict(x_test)

In [48]:
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

print("Training R2 Score:", train_r2)
print("Testing R2 Score:", test_r2)

Training R2 Score: 1.0
Testing R2 Score: 0.7690584033156069

In [49]:
train_mse = mean_squared_error(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
print("Training Mean squared error: ", train_mse)
print("Testing Mean squared error: ", test_mse)

Training Mean squared error:  0.0
Testing Mean squared error:  156290931.42334518

In [50]:
train_rmse = np.sqrt(train_mse)
test_rmse = np.sqrt(test_mse)
print("Training Root mean squared error: ", train_rmse)
print("Testing Root mean squared error: ", test_rmse)

Training Root mean squared error:  0.0
Testing Root mean squared error:  12501.637149723438

In [51]:
joblib.dump(best_knn, "knn.pkl")

['knn.pkl']